title: Writing software for joy
description: Zababako Studio Inc.

show_downloads: false
google_analytics: UA-127940472-1

url: https://www.zababako.com

markdown: kramdown
theme: jekyll-theme-cayman

# Contacts
email: hello@zababako.com